name: Shimirel
favicon: null
layout_spectrum: 0.4212883892469108
typography_spectrum: 0.6958227206487209
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.6790938905905932
  lightness: 0.22752596926875412
  saturation: 0.44102125777862966
  rhythmicContrast: 0.46427579154260457
purpose: []
